method: no_cot
base_model: meta-llama/Llama-3.2-1B-Instruct
template_path: template/template.txt
output_dir: outputs/no_cot

data:
  train_path: data/gsm8k/aug_train.jsonl
  eval_path: data/gsm8k/test.jsonl
  validation_ratio: 0.01
  max_train_samples:
  max_eval_samples:

checkpoint:
  resume_from_checkpoint:
  eval_checkpoint:
  cot_init_checkpoint: checkpoints/llama3.2-1b_lora_cot_gsm-aug

training:
  num_train_epochs: 25
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-4
  weight_decay: 0.01
  lr_scheduler_type: cosine
  warmup_steps: 0.03
  bf16: true
  logging_steps: 10
  eval_strategy: epoch
  save_strategy: epoch
  save_total_limit: 3
  report_to: tensorboard
